apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    app: backend-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
      - name: backend-feed
        image: badex360/udagram-api-feed:1.0.0
        ports:
        - containerPort: 8080
        env: 
        - name: POSTGRES_USERNAME
          valueFrom: 
            secretKeyRef: 
              name: env-secret
              key: postgres-username

        - name: POSTGRES_PASSWORD
          valueFrom: 
            secretKeyRef: 
              name: env-secret
              key: postgres-password

        - name: JWT_SECRET
          valueFrom: 
            secretKeyRef: 
              name: env-secret
              key: jwt-secret

        - name: AWS_PROFILE
          valueFrom: 
            secretKeyRef: 
              name: env-secret
              key: aws-profile

        - name: AWS_ACCESS_KEY_ID
          valueFrom: 
            secretKeyRef: 
              name: aws-secret
              key: aws-access-key-id

        - name: AWS_SECRET_ACCESS_KEY
          valueFrom: 
            secretKeyRef: 
              name: aws-secret
              key: aws-secret-access-key

        - name: AWS_BUCKET
          valueFrom: 
            configMapKeyRef: 
              name: udagram-configmap
              key: aws-bucket


        - name: AWS_REGION
          valueFrom: 
            configMapKeyRef: 
              name: udagram-configmap
              key: aws-region


        - name: POSTGRES_DB
          valueFrom: 
            configMapKeyRef: 
              name: udagram-configmap
              key: postgres-db


        - name: POSTGRES_HOST
          valueFrom: 
            configMapKeyRef: 
              name: udagram-configmap
              key: postgres-host
---
apiVersion: v1
kind: Service
metadata:
  name: backend-feed 
  labels:
    app: backend-feed 
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: backend-feed

      