version: "3"
services:
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: reverseproxy:1.0.0
  backend_user:
    build:
      context: ./udagram-api-user
    image: udagram-api-user:1.0.0
  backend_feed:
    build:
      context: ./udagram-api-feed
    image: udagram-api-feed:1.0.0
  frontend:
    build:
      context: ./udagram-frontend
    image: udagram-frontend:1.0.0
